name: 5CentPhotos
favicon: null
layout_spectrum: 0.10038158390671015
typography_spectrum: 0.1148
title: worth every penny
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#131313'
    - '#e6e6e6'
    - '#2597c7'
    - '#606060'
    - '#aaaaaa'
  brandStrength: 0.8558714892715216
  lightness: 0.2660463380161673
  saturation: 0.4460507135372609
  rhythmicContrast: 0.05450101103633642
purpose: []
